#!/usr/bin/env bash
#install ngix and put holberton inside

sudo apt-get -y update
sudo apt-get -y install nginx
mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
