#!/usr/bin/env bash
# Configure Nginx server to give error 404 page
sudo apt-get update
sudo apt-get -y install nginx
mkdir -p /etc/nginx/html /var/www/html
touch /etc/nginx/html/index.html
touch /var/www/html/404.html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    sever_name softartz.tech;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html {
    root /var/www/html;
		internal;
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
