#!/usr/bin/env bash
# Create a script to create a mysql db backup and convert to tar.gz format using todays date
mysqldump -u root -p"$1" --all-databases >backup.sql 2>/dev/null
tar -cvzf "$(date +%m-%d-%Y).tar.gz" ./backup.sql
